### ISSUE TITLE
Ball Tracking

### ISSUE THREAD

**Issue by dimitriasilveria** [HumanoidPequi/HumanoidPMec_LARC2023#4]

**Comment by dimitriasilveria** [comment]
- [ ] Train Yolo object detection
- [ ] Use box coordinates to estimate xy ball position
- [ ] Calculate the necessary angular displacement to align the camera center with the ball
- [ ] Send this angle to the servos via ros
- [ ] Use optical flow to ensure the ball keeps aligned
- [ ] Read head pitch angle from IMU information (via ROS)
- [ ] Distance estimation

**Comment by dimitriasilveria** [comment]
@andrecaraiba we need the IMU readings as soon as possible, please
